import React from 'react';
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';
import IncaricoView from '../IncaricoView/IncaricoView';
import configureStore from 'redux-mock-store';
import { Provider } from 'react-intl-redux';
import { MemoryRouter } from 'react-router-dom';
import thunk from 'redux-thunk';

const middlewares = [thunk];
const mockStore = configureStore(middlewares);

// Warning: An update to Icon inside a test was not wrapped in act(...).
// When testing, code that causes React state updates should be wrapped into act(...):
jest.mock('design-comuni-plone-theme/components/ItaliaTheme/Icons/Icon');
jest.mock('@plone/volto/helpers/Loadable/Loadable');
beforeAll(
  async () =>
    await require('@plone/volto/helpers/Loadable/Loadable').__setLoadables(),
);

const mock_mandatory = {
  '@id': 'http://localhost:3000/amministrazione/incarichi/band-leader',
  '@type': 'Incarico',
  UID: '8c78f57d21ae461bb44fe8d6e93ad4a7',
  data_inizio_incarico: '2023-01-26',
  items: [],
  tipologia_incarico: {
    title: 'Altro',
    token: 'altro',
  },
  title: 'Band leader',
};

const mock_allfields = {
  ...mock_mandatory,
  '@components': {
    actions: {
      '@id':
        'http://localhost:3000/amministrazione/incarichi/band-leader/@actions',
    },
    aliases: {
      '@id':
        'http://localhost:3000/amministrazione/incarichi/band-leader/@aliases',
    },
    breadcrumbs: {
      '@id':
        'http://localhost:3000/amministrazione/incarichi/band-leader/@breadcrumbs',
    },
    contextnavigation: {
      '@id':
        'http://localhost:3000/amministrazione/incarichi/band-leader/@contextnavigation',
    },
    navigation: {
      '@id':
        'http://localhost:3000/amministrazione/incarichi/band-leader/@navigation',
    },
    subsite: {},
    translations: {
      '@id':
        'http://localhost:3000/amministrazione/incarichi/band-leader/@translations',
    },
    types: {
      '@id':
        'http://localhost:3000/amministrazione/incarichi/band-leader/@types',
    },
    workflow: {
      '@id':
        'http://localhost:3000/amministrazione/incarichi/band-leader/@workflow',
    },
  },
  '@id': 'http://localhost:3000/amministrazione/incarichi/band-leader',
  '@type': 'Incarico',
  UID: '8c78f57d21ae461bb44fe8d6e93ad4a7',
  allow_discussion: false,
  atto_nomina: [],
  changeNote: '',
  compensi: {
    blocks: {
      'f8497932-a912-489e-b3f9-98fb03b8afd5': {
        '@type': 'text',
        text: {
          blocks: [
            {
              data: {},
              depth: 0,
              entityRanges: [],
              inlineStyleRanges: [],
              key: 'cc94j',
              text: 'My time has come',
              type: 'unstyled',
            },
          ],
          entityMap: {},
        },
      },
    },
    blocks_layout: {
      items: ['f8497932-a912-489e-b3f9-98fb03b8afd5'],
    },
  },
  contributors: [],
  created: '2023-01-30T15:44:07+00:00',
  creators: ['admin'],
  data_conclusione_incarico: '2023-03-31',
  data_insediamento: '2023-01-31',
  description: 'Too late',
  design_italia_meta_type: 'Incarico',
  effective: null,
  exclude_from_nav: false,
  expires: null,
  id: 'band-leader',
  importi_viaggio_servizio: {
    blocks: {
      'b3a6778b-cd82-4ff5-822d-da57dc47b679': {
        '@type': 'text',
        text: {
          blocks: [
            {
              data: {},
              depth: 0,
              entityRanges: [],
              inlineStyleRanges: [],
              key: 'bcdll',
              text: 'Sends shivers down my spine',
              type: 'unstyled',
            },
          ],
          entityMap: {},
        },
      },
    },
    blocks_layout: {
      items: ['b3a6778b-cd82-4ff5-822d-da57dc47b679'],
    },
  },
  is_folderish: true,
  items: [
    {
      '@id':
        'http://localhost:3000/amministrazione/incarichi/band-leader/compensi-file',
      '@type': 'Document',
      description: '',
      design_italia_meta_type: 'Pagina',
      has_children: false,
      id: 'compensi-file',
      image_field: '',
      image_scales: null,
      review_state: 'private',
      title: 'Compensi',
    },
    {
      '@id':
        'http://localhost:3000/amministrazione/incarichi/band-leader/importi-di-viaggio-e-o-servizi',
      '@type': 'Document',
      description: '',
      design_italia_meta_type: 'Pagina',
      has_children: false,
      id: 'importi-di-viaggio-e-o-servizi',
      image_field: '',
      image_scales: null,
      review_state: 'private',
      title: 'Importi di viaggio e/o servizi',
    },
  ],
  items_total: 2,
  language: {
    title: 'Italiano',
    token: 'it',
  },
  layout: 'view',
  lock: {
    locked: false,
    stealable: true,
  },
  modified: '2023-01-30T15:44:08+00:00',
  next_item: {},
  opengraph_description: null,
  opengraph_image: null,
  opengraph_title: null,
  parent: {
    '@id': 'http://localhost:3000/amministrazione/incarichi',
    '@type': 'Document',
    description: '',
    design_italia_meta_type: 'Pagina',
    has_children: true,
    id: 'incarichi',
    image_field: null,
    image_scales: null,
    review_state: 'private',
    title: 'Incarichi',
  },
  persona: [
    {
      '@id':
        'http://localhost:3000/amministrazione/personale-amministrativo/gianluca-luchetti',
      '@type': 'Persona',
      description: 'Is this the real life?',
      design_italia_meta_type: 'Persona pubblica',
      effective: null,
      has_children: true,
      id: 'gianluca-luchetti',
      image_field: 'foto_persona',
      image_scales: {
        foto_persona: [
          {
            'content-type': 'image/jpeg',
            download:
              'http://localhost:3000/amministrazione/personale-amministrativo/gianluca-luchetti/@@images/foto_persona-6240-d31400b093b5122378386bfcbfcbadef.jpeg',
            filename: 'woman-having-online-meeting-work.jpg',
            height: 4160,
            scales: {
              gallery: {
                download:
                  'http://localhost:3000/amministrazione/personale-amministrativo/gianluca-luchetti/@@images/foto_persona-250-4415efecba55f5c3b7855d316c282803.jpeg',
                height: 166,
                width: 250,
              },
              great: {
                download:
                  'http://localhost:3000/amministrazione/personale-amministrativo/gianluca-luchetti/@@images/foto_persona-1200-8362c0aa18afb393870557831338e877.jpeg',
                height: 800,
                width: 1200,
              },
              huge: {
                download:
                  'http://localhost:3000/amministrazione/personale-amministrativo/gianluca-luchetti/@@images/foto_persona-1600-5870178455c80ebd71ab45f2ad13a723.jpeg',
                height: 1066,
                width: 1600,
              },
              icon: {
                download:
                  'http://localhost:3000/amministrazione/personale-amministrativo/gianluca-luchetti/@@images/foto_persona-32-5ca5f6d23481ec4c66837ea5651e7d36.jpeg',
                height: 21,
                width: 32,
              },
              large: {
                download:
                  'http://localhost:3000/amministrazione/personale-amministrativo/gianluca-luchetti/@@images/foto_persona-800-68fd8822e74c7ae1a2543164ddd90893.jpeg',
                height: 533,
                width: 800,
              },
              larger: {
                download:
                  'http://localhost:3000/amministrazione/personale-amministrativo/gianluca-luchetti/@@images/foto_persona-1000-9eff05079ce70e130cf0933f7a452d51.jpeg',
                height: 666,
                width: 1000,
              },
              listing: {
                download:
                  'http://localhost:3000/amministrazione/personale-amministrativo/gianluca-luchetti/@@images/foto_persona-16-b38ed561b94559c62ae52844b0d1047b.jpeg',
                height: 10,
                width: 16,
              },
              midi: {
                download:
                  'http://localhost:3000/amministrazione/personale-amministrativo/gianluca-luchetti/@@images/foto_persona-300-a55ee7f9e782c431b17d7235120ed3d8.jpeg',
                height: 200,
                width: 300,
              },
              mini: {
                download:
                  'http://localhost:3000/amministrazione/personale-amministrativo/gianluca-luchetti/@@images/foto_persona-200-0709de767e7a6265ef39e5487a2e56a1.jpeg',
                height: 133,
                width: 200,
              },
              preview: {
                download:
                  'http://localhost:3000/amministrazione/personale-amministrativo/gianluca-luchetti/@@images/foto_persona-400-5eeb9a3af2c47d6706343b334c38961c.jpeg',
                height: 266,
                width: 400,
              },
              teaser: {
                download:
                  'http://localhost:3000/amministrazione/personale-amministrativo/gianluca-luchetti/@@images/foto_persona-600-75da0c04427678563fc513045d897d12.jpeg',
                height: 400,
                width: 600,
              },
              thumb: {
                download:
                  'http://localhost:3000/amministrazione/personale-amministrativo/gianluca-luchetti/@@images/foto_persona-128-3ae9e59c013b3ac965c5dd6b0ad1734b.jpeg',
                height: 85,
                width: 128,
              },
              tile: {
                download:
                  'http://localhost:3000/amministrazione/personale-amministrativo/gianluca-luchetti/@@images/foto_persona-64-beefd05f0c84aa0004daf27d1a940e6c.jpeg',
                height: 42,
                width: 64,
              },
            },
            size: 1195679,
            width: 6240,
          },
        ],
      },
      incarichi: 'Incaricone',
      review_state: 'private',
      title: 'Gianluca Luchetti',
    },
  ],
  previous_item: {},
  relatedItems: [],
  responsabile_struttura: [
    {
      '@id': 'http://localhost:3000/amministrazione/politici/ctm-cagliari-1',
      '@type': 'UnitaOrganizzativa',
      address: '',
      circoscrizione: null,
      city: null,
      contact_info: [
        {
          '@id': 'http://localhost:3000/amministrazione/politici/ctm-cagliari',
          '@type': 'PuntoDiContatto',
          description: '',
          design_italia_meta_type: 'Punto di Contatto',
          has_children: false,
          id: 'ctm-cagliari',
          image_field: null,
          image_scales: null,
          review_state: 'private',
          title: 'CTM Cagliari',
          value_punto_contatto: [
            {
              pdc_type: 'web',
              pdc_value: 'https://www.ctmcagliari.it/en/',
            },
          ],
        },
      ],
      description: '',
      design_italia_meta_type: 'Unita Organizzativa',
      effective: null,
      geolocation: {
        latitude: 0,
        longitude: 0,
      },
      has_children: true,
      id: 'ctm-cagliari-1',
      image_field: null,
      image_scales: null,
      nome_sede: null,
      quartiere: null,
      review_state: 'private',
      street: null,
      title: 'CTM Cagliari',
      zip_code: null,
    },
  ],
  review_state: 'private',
  rights: '',
  seo_canonical_url: null,
  seo_description: null,
  seo_noindex: null,
  seo_title: null,
  subjects: [],
  ulteriori_informazioni: {
    blocks: {},
    blocks_layout: {
      items: [],
    },
  },
  unita_organizzativa: [
    {
      '@id':
        'http://localhost:3000/amministrazione/aree-di-competenza/area-impiantistica-sportiva-e-manifestazioni-sportive',
      '@type': 'UnitaOrganizzativa',
      address: '',
      circoscrizione: null,
      city: null,
      contact_info: {
        blocks: {
          'c6feaad0-4f8e-411a-8e2a-f9fbe644dc55': {
            '@type': 'text',
          },
        },
        blocks_layout: {
          items: ['c6feaad0-4f8e-411a-8e2a-f9fbe644dc55'],
        },
      },
      description: 'Dirigente Arch. M. Alessandra Verdi',
      design_italia_meta_type: 'Unita Organizzativa',
      effective: null,
      geolocation: {
        latitude: 0,
        longitude: 0,
      },
      has_children: true,
      id: 'area-impiantistica-sportiva-e-manifestazioni-sportive',
      image_field: null,
      image_scales: null,
      nome_sede: null,
      quartiere: null,
      review_state: 'private',
      street: null,
      title: 'Area impiantistica sportiva e manifestazioni sportive',
      zip_code: null,
    },
  ],
  version: 'current',
  versioning_enabled: true,
  working_copy: null,
  working_copy_of: null,
};

const store = mockStore({
  intl: {
    locale: 'en',
    messages: {},
  },
  content: {
    subrequests: {},
  },
  search: {
    error: null,
    items: [
      {
        '@id': '/amministrazione/politici',
        '@type': 'Document',
        CreationDate: '2023-01-03T16:14:59+00:00',
        Creator: 'admin',
        Date: '2023-01-04T13:53:12+00:00',
        Description: '',
        EffectiveDate: 'None',
        ExpirationDate: 'None',
        ModificationDate: '2023-01-04T13:53:12+00:00',
        Subject: [],
        Subject_bando: null,
        Title: 'Politici',
        Type: 'Pagina',
        UID: 'e0e4dd7a1f7b49468f6c46e78343831e',
        apertura_bando: null,
        author_name: null,
        chiusura_procedimento_bando: null,
        cmf_uid: 35,
        commentators: [],
        created: '2023-01-03T16:14:59+00:00',
        data_conclusione_incarico: null,
        description: '',
        design_italia_meta_type: 'Pagina',
        destinatari_bando: null,
        effective: null,
        end: null,
        ente_bando: null,
        event_location: null,
        exclude_from_nav: false,
        expires: null,
        geolocation: null,
        getIcon: false,
        getId: 'politici',
        getObjSize: '0 KB',
        getPath: '/Plone/amministrazione/politici',
        getRemoteUrl: null,
        getURL: 'http://localhost:3000/amministrazione/politici',
        hasPreviewImage: null,
        head_title: null,
        icona: null,
        id: 'politici',
        image_field: '',
        image_scales: null,
        in_response_to: null,
        is_folderish: true,
        last_comment_date: null,
        latitude: null,
        listCreators: ['admin'],
        location: null,
        longitude: null,
        mime_type: 'text/plain',
        modified: '2023-01-04T13:53:12+00:00',
        nav_title: null,
        open_end: null,
        parent: {
          '@id': 'http://localhost:3000/amministrazione',
          UID: '0af0cc387e024824a1b896c4db408688',
          title: 'Amministrazione',
        },
        portal_type: 'Document',
        recurrence: null,
        review_state: 'private',
        scadenza_bando: null,
        start: null,
        sync_uid: null,
        tassonomia_argomenti: [],
        taxonomy_business_events: null,
        taxonomy_person_life_events: null,
        taxonomy_temi_dataset: null,
        taxonomy_tipologia_documenti_albopretorio: null,
        taxonomy_tipologia_documento: null,
        taxonomy_tipologia_evento: null,
        taxonomy_tipologia_frequenza_aggiornamento: null,
        taxonomy_tipologia_incarico: null,
        taxonomy_tipologia_licenze: null,
        taxonomy_tipologia_luogo: null,
        taxonomy_tipologia_notizia: null,
        taxonomy_tipologia_organizzazione: null,
        taxonomy_tipologia_pdc: null,
        taxonomy_tipologia_stati_pratica: null,
        tipologia_bando: null,
        tipologia_documento: null,
        tipologia_notizia: null,
        title: 'Politici',
        total_comments: 0,
        ufficio_responsabile_bando: null,
        update_note: null,
        whole_day: null,
      },
      {
        '@id': '/amministrazione/personale-amministrativo',
        '@type': 'Document',
        CreationDate: '2023-01-03T16:14:59+00:00',
        Creator: 'admin',
        Date: '2023-01-26T14:28:10+00:00',
        Description: '',
        EffectiveDate: 'None',
        ExpirationDate: 'None',
        ModificationDate: '2023-01-26T14:28:10+00:00',
        Subject: [],
        Subject_bando: null,
        Title: 'Personale Amministrativo',
        Type: 'Pagina',
        UID: '449f971ea52a4980b9e3ec9f8cdd04ce',
        apertura_bando: null,
        author_name: null,
        chiusura_procedimento_bando: null,
        cmf_uid: 36,
        commentators: [],
        created: '2023-01-03T16:14:59+00:00',
        data_conclusione_incarico: null,
        description: '',
        design_italia_meta_type: 'Pagina',
        destinatari_bando: null,
        effective: null,
        end: null,
        ente_bando: null,
        event_location: null,
        exclude_from_nav: false,
        expires: null,
        geolocation: null,
        getIcon: false,
        getId: 'personale-amministrativo',
        getObjSize: '0 KB',
        getPath: '/Plone/amministrazione/personale-amministrativo',
        getRemoteUrl: null,
        getURL:
          'http://localhost:3000/amministrazione/personale-amministrativo',
        hasPreviewImage: null,
        head_title: null,
        icona: null,
        id: 'personale-amministrativo',
        image_field: '',
        image_scales: null,
        in_response_to: null,
        is_folderish: true,
        last_comment_date: null,
        latitude: null,
        listCreators: ['admin'],
        location: null,
        longitude: null,
        mime_type: 'text/plain',
        modified: '2023-01-26T14:28:10+00:00',
        nav_title: null,
        open_end: null,
        parent: {
          '@id': 'http://localhost:3000/amministrazione',
          UID: '0af0cc387e024824a1b896c4db408688',
          title: 'Amministrazione',
        },
        portal_type: 'Document',
        recurrence: null,
        review_state: 'private',
        scadenza_bando: null,
        start: null,
        sync_uid: null,
        tassonomia_argomenti: [],
        taxonomy_business_events: [],
        taxonomy_person_life_events: [],
        taxonomy_temi_dataset: [],
        taxonomy_tipologia_documenti_albopretorio: [],
        taxonomy_tipologia_documento: [],
        taxonomy_tipologia_evento: [],
        taxonomy_tipologia_frequenza_aggiornamento: [],
        taxonomy_tipologia_incarico: [],
        taxonomy_tipologia_licenze: [],
        taxonomy_tipologia_luogo: [],
        taxonomy_tipologia_notizia: [],
        taxonomy_tipologia_organizzazione: [],
        taxonomy_tipologia_pdc: [],
        taxonomy_tipologia_stati_pratica: [],
        tipologia_bando: null,
        tipologia_documento: null,
        tipologia_notizia: null,
        title: 'Personale Amministrativo',
        total_comments: 0,
        ufficio_responsabile_bando: null,
        update_note: null,
        whole_day: null,
      },
      {
        '@id': '/amministrazione/organi-di-governo',
        '@type': 'Document',
        CreationDate: '2023-01-03T16:14:59+00:00',
        Creator: 'admin',
        Date: '2023-01-03T16:14:59+00:00',
        Description: '',
        EffectiveDate: 'None',
        ExpirationDate: 'None',
        ModificationDate: '2023-01-03T16:14:59+00:00',
        Subject: [],
        Subject_bando: null,
        Title: 'Organi di governo',
        Type: 'Pagina',
        UID: '818b3643b0b54700b59f46f44d4805c3',
        apertura_bando: null,
        author_name: null,
        chiusura_procedimento_bando: null,
        cmf_uid: 37,
        commentators: [],
        created: '2023-01-03T16:14:59+00:00',
        data_conclusione_incarico: null,
        description: '',
        design_italia_meta_type: 'Pagina',
        destinatari_bando: null,
        effective: null,
        end: null,
        ente_bando: null,
        event_location: null,
        exclude_from_nav: false,
        expires: null,
        geolocation: null,
        getIcon: false,
        getId: 'organi-di-governo',
        getObjSize: '0 KB',
        getPath: '/Plone/amministrazione/organi-di-governo',
        getRemoteUrl: null,
        getURL: 'http://localhost:3000/amministrazione/organi-di-governo',
        hasPreviewImage: null,
        head_title: null,
        icona: null,
        id: 'organi-di-governo',
        image_field: '',
        image_scales: null,
        in_response_to: null,
        is_folderish: true,
        last_comment_date: null,
        latitude: null,
        listCreators: ['admin'],
        location: null,
        longitude: null,
        mime_type: 'text/plain',
        modified: '2023-01-03T16:14:59+00:00',
        nav_title: null,
        open_end: null,
        parent: {
          '@id': 'http://localhost:8080/Plone/amministrazione',
          UID: '0af0cc387e024824a1b896c4db408688',
          title: 'Amministrazione',
        },
        portal_type: 'Document',
        recurrence: null,
        review_state: 'private',
        scadenza_bando: null,
        start: null,
        sync_uid: null,
        tassonomia_argomenti: [],
        taxonomy_business_events: null,
        taxonomy_person_life_events: null,
        taxonomy_temi_dataset: null,
        taxonomy_tipologia_documenti_albopretorio: null,
        taxonomy_tipologia_documento: null,
        taxonomy_tipologia_evento: null,
        taxonomy_tipologia_frequenza_aggiornamento: null,
        taxonomy_tipologia_incarico: null,
        taxonomy_tipologia_licenze: null,
        taxonomy_tipologia_luogo: null,
        taxonomy_tipologia_notizia: null,
        taxonomy_tipologia_organizzazione: null,
        taxonomy_tipologia_pdc: null,
        taxonomy_tipologia_stati_pratica: null,
        tipologia_bando: null,
        tipologia_documento: null,
        tipologia_notizia: null,
        title: 'Organi di governo',
        total_comments: 0,
        ufficio_responsabile_bando: null,
        update_note: null,
        whole_day: null,
      },
      {
        '@id': '/amministrazione/aree-amministrative',
        '@type': 'Document',
        CreationDate: '2023-01-03T16:14:59+00:00',
        Creator: 'admin',
        Date: '2023-01-04T15:59:28+00:00',
        Description:
          'La struttura organizzativa è suddivisa in aree di competenze che gestiscono i servizi erogati alla comunità.  ',
        EffectiveDate: 'None',
        ExpirationDate: 'None',
        ModificationDate: '2023-01-04T15:59:28+00:00',
        Subject: [],
        Subject_bando: null,
        Title: 'Aree amministrative',
        Type: 'Pagina',
        UID: '723e605e646e47139e9e40267229d207',
        apertura_bando: null,
        author_name: null,
        chiusura_procedimento_bando: null,
        cmf_uid: 38,
        commentators: [],
        created: '2023-01-03T16:14:59+00:00',
        data_conclusione_incarico: null,
        description:
          'La struttura organizzativa è suddivisa in aree di competenze che gestiscono i servizi erogati alla comunità.  ',
        design_italia_meta_type: 'Pagina',
        destinatari_bando: null,
        effective: null,
        end: null,
        ente_bando: null,
        event_location: null,
        exclude_from_nav: false,
        expires: null,
        geolocation: null,
        getIcon: false,
        getId: 'aree-amministrative',
        getObjSize: '1 KB',
        getPath: '/Plone/amministrazione/aree-amministrative',
        getRemoteUrl: null,
        getURL: 'http://localhost:3000/amministrazione/aree-amministrative',
        hasPreviewImage: null,
        head_title: null,
        icona: null,
        id: 'aree-amministrative',
        image_field: '',
        image_scales: null,
        in_response_to: null,
        is_folderish: true,
        last_comment_date: null,
        latitude: null,
        listCreators: ['admin'],
        location: null,
        longitude: null,
        mime_type: 'text/plain',
        modified: '2023-01-04T15:59:28+00:00',
        nav_title: null,
        open_end: null,
        parent: {
          '@id': 'http://localhost:3000/amministrazione',
          UID: '0af0cc387e024824a1b896c4db408688',
          title: 'Amministrazione',
        },
        portal_type: 'Document',
        recurrence: null,
        review_state: 'private',
        scadenza_bando: null,
        start: null,
        sync_uid: null,
        tassonomia_argomenti: [],
        taxonomy_business_events: null,
        taxonomy_person_life_events: null,
        taxonomy_temi_dataset: null,
        taxonomy_tipologia_documenti_albopretorio: null,
        taxonomy_tipologia_documento: null,
        taxonomy_tipologia_evento: null,
        taxonomy_tipologia_frequenza_aggiornamento: null,
        taxonomy_tipologia_incarico: null,
        taxonomy_tipologia_licenze: null,
        taxonomy_tipologia_luogo: null,
        taxonomy_tipologia_notizia: null,
        taxonomy_tipologia_organizzazione: null,
        taxonomy_tipologia_pdc: null,
        taxonomy_tipologia_stati_pratica: null,
        tipologia_bando: null,
        tipologia_documento: null,
        tipologia_notizia: null,
        title: 'Aree amministrative',
        total_comments: 0,
        ufficio_responsabile_bando: null,
        update_note: null,
        whole_day: null,
      },
      {
        '@id': '/amministrazione/uffici',
        '@type': 'Document',
        CreationDate: '2023-01-03T16:14:59+00:00',
        Creator: 'admin',
        Date: '2023-01-04T13:44:40+00:00',
        Description: '',
        EffectiveDate: 'None',
        ExpirationDate: 'None',
        ModificationDate: '2023-01-04T13:44:40+00:00',
        Subject: [],
        Subject_bando: null,
        Title: 'Uffici',
        Type: 'Pagina',
        UID: 'fb75779ea5c24d7189d50f98ccc1060c',
        apertura_bando: null,
        author_name: null,
        chiusura_procedimento_bando: null,
        cmf_uid: 39,
        commentators: [],
        created: '2023-01-03T16:14:59+00:00',
        data_conclusione_incarico: null,
        description: '',
        design_italia_meta_type: 'Pagina',
        destinatari_bando: null,
        effective: null,
        end: null,
        ente_bando: null,
        event_location: null,
        exclude_from_nav: false,
        expires: null,
        geolocation: null,
        getIcon: false,
        getId: 'uffici',
        getObjSize: '0 KB',
        getPath: '/Plone/amministrazione/uffici',
        getRemoteUrl: null,
        getURL: 'http://localhost:3000/amministrazione/uffici',
        hasPreviewImage: null,
        head_title: null,
        icona: null,
        id: 'uffici',
        image_field: '',
        image_scales: null,
        in_response_to: null,
        is_folderish: true,
        last_comment_date: null,
        latitude: null,
        listCreators: ['admin'],
        location: null,
        longitude: null,
        mime_type: 'text/plain',
        modified: '2023-01-04T13:44:40+00:00',
        nav_title: null,
        open_end: null,
        parent: {
          '@id': 'http://localhost:3000/amministrazione',
          UID: '0af0cc387e024824a1b896c4db408688',
          title: 'Amministrazione',
        },
        portal_type: 'Document',
        recurrence: null,
        review_state: 'private',
        scadenza_bando: null,
        start: null,
        sync_uid: null,
        tassonomia_argomenti: [],
        taxonomy_business_events: null,
        taxonomy_person_life_events: null,
        taxonomy_temi_dataset: null,
        taxonomy_tipologia_documenti_albopretorio: null,
        taxonomy_tipologia_documento: null,
        taxonomy_tipologia_evento: null,
        taxonomy_tipologia_frequenza_aggiornamento: null,
        taxonomy_tipologia_incarico: null,
        taxonomy_tipologia_licenze: null,
        taxonomy_tipologia_luogo: null,
        taxonomy_tipologia_notizia: null,
        taxonomy_tipologia_organizzazione: null,
        taxonomy_tipologia_pdc: null,
        taxonomy_tipologia_stati_pratica: null,
        tipologia_bando: null,
        tipologia_documento: null,
        tipologia_notizia: null,
        title: 'Uffici',
        total_comments: 0,
        ufficio_responsabile_bando: null,
        update_note: null,
        whole_day: null,
      },
      {
        '@id': '/amministrazione/enti-e-fondazioni',
        '@type': 'Document',
        CreationDate: '2023-01-03T16:14:59+00:00',
        Creator: 'admin',
        Date: '2023-01-04T13:42:14+00:00',
        Description: '',
        EffectiveDate: 'None',
        ExpirationDate: 'None',
        ModificationDate: '2023-01-04T13:42:14+00:00',
        Subject: [],
        Subject_bando: null,
        Title: 'Enti e fondazioni',
        Type: 'Pagina',
        UID: '6773a7187c4040f694caa7d29cdf8807',
        apertura_bando: null,
        author_name: null,
        chiusura_procedimento_bando: null,
        cmf_uid: 40,
        commentators: [],
        created: '2023-01-03T16:14:59+00:00',
        data_conclusione_incarico: null,
        description: '',
        design_italia_meta_type: 'Pagina',
        destinatari_bando: null,
        effective: null,
        end: null,
        ente_bando: null,
        event_location: null,
        exclude_from_nav: false,
        expires: null,
        geolocation: null,
        getIcon: false,
        getId: 'enti-e-fondazioni',
        getObjSize: '0 KB',
        getPath: '/Plone/amministrazione/enti-e-fondazioni',
        getRemoteUrl: null,
        getURL: 'http://localhost:3000/amministrazione/enti-e-fondazioni',
        hasPreviewImage: null,
        head_title: null,
        icona: null,
        id: 'enti-e-fondazioni',
        image_field: '',
        image_scales: null,
        in_response_to: null,
        is_folderish: true,
        last_comment_date: null,
        latitude: null,
        listCreators: ['admin'],
        location: null,
        longitude: null,
        mime_type: 'text/plain',
        modified: '2023-01-04T13:42:14+00:00',
        nav_title: null,
        open_end: null,
        parent: {
          '@id': 'http://localhost:3000/amministrazione',
          UID: '0af0cc387e024824a1b896c4db408688',
          title: 'Amministrazione',
        },
        portal_type: 'Document',
        recurrence: null,
        review_state: 'private',
        scadenza_bando: null,
        start: null,
        sync_uid: null,
        tassonomia_argomenti: [],
        taxonomy_business_events: null,
        taxonomy_person_life_events: null,
        taxonomy_temi_dataset: null,
        taxonomy_tipologia_documenti_albopretorio: null,
        taxonomy_tipologia_documento: null,
        taxonomy_tipologia_evento: null,
        taxonomy_tipologia_frequenza_aggiornamento: null,
        taxonomy_tipologia_incarico: null,
        taxonomy_tipologia_licenze: null,
        taxonomy_tipologia_luogo: null,
        taxonomy_tipologia_notizia: null,
        taxonomy_tipologia_organizzazione: null,
        taxonomy_tipologia_pdc: null,
        taxonomy_tipologia_stati_pratica: null,
        tipologia_bando: null,
        tipologia_documento: null,
        tipologia_notizia: null,
        title: 'Enti e fondazioni',
        total_comments: 0,
        ufficio_responsabile_bando: null,
        update_note: null,
        whole_day: null,
      },
      {
        '@id': '/amministrazione/luoghi',
        '@type': 'Document',
        CreationDate: '2023-01-03T16:14:59+00:00',
        Creator: 'admin',
        Date: '2023-01-03T16:14:59+00:00',
        Description: '',
        EffectiveDate: 'None',
        ExpirationDate: 'None',
        ModificationDate: '2023-01-03T16:14:59+00:00',
        Subject: [],
        Subject_bando: null,
        Title: 'Luoghi',
        Type: 'Pagina',
        UID: '65c84499d5474cd7b736181c531bfa28',
        apertura_bando: null,
        author_name: null,
        chiusura_procedimento_bando: null,
        cmf_uid: 41,
        commentators: [],
        created: '2023-01-03T16:14:59+00:00',
        data_conclusione_incarico: null,
        description: '',
        design_italia_meta_type: 'Pagina',
        destinatari_bando: null,
        effective: null,
        end: null,
        ente_bando: null,
        event_location: null,
        exclude_from_nav: false,
        expires: null,
        geolocation: null,
        getIcon: false,
        getId: 'luoghi',
        getObjSize: '0 KB',
        getPath: '/Plone/amministrazione/luoghi',
        getRemoteUrl: null,
        getURL: 'http://localhost:3000/amministrazione/luoghi',
        hasPreviewImage: null,
        head_title: null,
        icona: null,
        id: 'luoghi',
        image_field: '',
        image_scales: null,
        in_response_to: null,
        is_folderish: true,
        last_comment_date: null,
        latitude: null,
        listCreators: ['admin'],
        location: null,
        longitude: null,
        mime_type: 'text/plain',
        modified: '2023-01-03T16:14:59+00:00',
        nav_title: null,
        open_end: null,
        parent: {
          '@id': 'http://localhost:8080/Plone/amministrazione',
          UID: '0af0cc387e024824a1b896c4db408688',
          title: 'Amministrazione',
        },
        portal_type: 'Document',
        recurrence: null,
        review_state: 'private',
        scadenza_bando: null,
        start: null,
        sync_uid: null,
        tassonomia_argomenti: [],
        taxonomy_business_events: null,
        taxonomy_person_life_events: null,
        taxonomy_temi_dataset: null,
        taxonomy_tipologia_documenti_albopretorio: null,
        taxonomy_tipologia_documento: null,
        taxonomy_tipologia_evento: null,
        taxonomy_tipologia_frequenza_aggiornamento: null,
        taxonomy_tipologia_incarico: null,
        taxonomy_tipologia_licenze: null,
        taxonomy_tipologia_luogo: null,
        taxonomy_tipologia_notizia: null,
        taxonomy_tipologia_organizzazione: null,
        taxonomy_tipologia_pdc: null,
        taxonomy_tipologia_stati_pratica: null,
        tipologia_bando: null,
        tipologia_documento: null,
        tipologia_notizia: null,
        title: 'Luoghi',
        total_comments: 0,
        ufficio_responsabile_bando: null,
        update_note: null,
        whole_day: null,
      },
      {
        '@id': '/amministrazione/aree-di-competenza',
        '@type': 'Document',
        CreationDate: '2023-01-03T16:24:55+00:00',
        Creator: 'admin',
        Date: '2023-01-03T16:32:16+00:00',
        Description: '',
        EffectiveDate: 'None',
        ExpirationDate: 'None',
        ModificationDate: '2023-01-03T16:32:16+00:00',
        Subject: [],
        Subject_bando: null,
        Title: 'Aree di competenza',
        Type: 'Pagina',
        UID: '4c2bca0d91e0485aa144c6a4ac5f2edf',
        apertura_bando: null,
        author_name: null,
        chiusura_procedimento_bando: null,
        cmf_uid: 74,
        commentators: [],
        created: '2023-01-03T16:24:55+00:00',
        data_conclusione_incarico: null,
        description: '',
        design_italia_meta_type: 'Pagina',
        destinatari_bando: null,
        effective: null,
        end: null,
        ente_bando: null,
        event_location: null,
        exclude_from_nav: false,
        expires: null,
        geolocation: null,
        getIcon: false,
        getId: 'aree-di-competenza',
        getObjSize: '1 KB',
        getPath: '/Plone/amministrazione/aree-di-competenza',
        getRemoteUrl: null,
        getURL: 'http://localhost:3000/amministrazione/aree-di-competenza',
        hasPreviewImage: null,
        head_title: null,
        icona: null,
        id: 'aree-di-competenza',
        image_field: '',
        image_scales: null,
        in_response_to: null,
        is_folderish: true,
        last_comment_date: null,
        latitude: null,
        listCreators: ['admin'],
        location: null,
        longitude: null,
        mime_type: 'text/plain',
        modified: '2023-01-03T16:32:16+00:00',
        nav_title: null,
        open_end: null,
        parent: {
          '@id': 'http://localhost:3000/amministrazione',
          UID: '0af0cc387e024824a1b896c4db408688',
          title: 'Amministrazione',
        },
        portal_type: 'Document',
        recurrence: null,
        review_state: 'private',
        scadenza_bando: null,
        start: null,
        sync_uid: null,
        tassonomia_argomenti: [],
        taxonomy_business_events: null,
        taxonomy_person_life_events: null,
        taxonomy_temi_dataset: null,
        taxonomy_tipologia_documenti_albopretorio: null,
        taxonomy_tipologia_documento: null,
        taxonomy_tipologia_evento: null,
        taxonomy_tipologia_frequenza_aggiornamento: null,
        taxonomy_tipologia_incarico: null,
        taxonomy_tipologia_licenze: null,
        taxonomy_tipologia_luogo: null,
        taxonomy_tipologia_notizia: null,
        taxonomy_tipologia_organizzazione: null,
        taxonomy_tipologia_pdc: null,
        taxonomy_tipologia_stati_pratica: null,
        tipologia_bando: null,
        tipologia_documento: null,
        tipologia_notizia: null,
        title: 'Aree di competenza',
        total_comments: 0,
        ufficio_responsabile_bando: null,
        update_note: null,
        whole_day: null,
      },
    ],
    total: 8,
    loaded: true,
    loading: false,
    batching: {},
    subrequests: {
      '1675088249497-multiple': {
        error: null,
        items: [
          {
            '@id':
              '/documenti-e-dati/documenti-albo-pretorio/bandi-per-impianti-e-manifestazioni',
            '@type': 'Documento',
            CreationDate: '2023-01-04T09:04:04+00:00',
            Creator: 'admin',
            Date: '2023-01-19T12:04:48+00:00',
            Description: 'Elenco bandi attivi',
            EffectiveDate: 'None',
            ExpirationDate: 'None',
            ModificationDate: '2023-01-19T12:04:48+00:00',
            Subject: [],
            Subject_bando: null,
            Title: 'Bandi per impianti e manifestazioni',
            Type: 'Documento',
            UID: 'ce2ff3fae38d47f5bdece9237cc47971',
            apertura_bando: null,
            author_name: null,
            chiusura_procedimento_bando: null,
            cmf_uid: 87,
            commentators: [],
            created: '2023-01-04T09:04:04+00:00',
            data_conclusione_incarico: null,
            description: 'Elenco bandi attivi',
            design_italia_meta_type: 'Documento',
            destinatari_bando: null,
            effective: null,
            end: null,
            ente_bando: null,
            event_location: null,
            exclude_from_nav: false,
            expires: null,
            geolocation: null,
            getIcon: false,
            getId: 'bandi-per-impianti-e-manifestazioni',
            getObjSize: '0 KB',
            getPath:
              '/Plone/documenti-e-dati/documenti-albo-pretorio/bandi-per-impianti-e-manifestazioni',
            getRemoteUrl: null,
            getURL:
              'http://localhost:3000/documenti-e-dati/documenti-albo-pretorio/bandi-per-impianti-e-manifestazioni',
            hasPreviewImage: null,
            head_title: null,
            icona: null,
            id: 'bandi-per-impianti-e-manifestazioni',
            image_field: '',
            image_scales: null,
            in_response_to: null,
            is_folderish: true,
            last_comment_date: null,
            latitude: null,
            listCreators: ['admin'],
            location: null,
            longitude: null,
            mime_type: 'text/plain',
            modified: '2023-01-19T12:04:48+00:00',
            nav_title: null,
            open_end: null,
            parent: {
              '@id':
                'http://localhost:8080/Plone/documenti-e-dati/documenti-albo-pretorio',
              UID: '5e6600a7ce2245199b0986471cffcf17',
              title: 'Documenti albo pretorio',
            },
            portal_type: 'Documento',
            recurrence: null,
            review_state: 'private',
            scadenza_bando: null,
            start: null,
            sync_uid: null,
            tassonomia_argomenti: [],
            taxonomy_business_events: [],
            taxonomy_person_life_events: [],
            taxonomy_temi_dataset: [],
            taxonomy_tipologia_documenti_albopretorio: [],
            taxonomy_tipologia_documento: [],
            taxonomy_tipologia_evento: [],
            taxonomy_tipologia_frequenza_aggiornamento: [],
            taxonomy_tipologia_incarico: [],
            taxonomy_tipologia_licenze: [],
            taxonomy_tipologia_luogo: [],
            taxonomy_tipologia_notizia: [],
            taxonomy_tipologia_organizzazione: [],
            taxonomy_tipologia_pdc: [],
            taxonomy_tipologia_stati_pratica: [],
            tipologia_bando: null,
            tipologia_documento: null,
            tipologia_notizia: null,
            title: 'Bandi per impianti e manifestazioni',
            total_comments: 0,
            ufficio_responsabile_bando: null,
            update_note: null,
            whole_day: null,
          },
          {
            '@id':
              '/documenti-e-dati/documenti-albo-pretorio/piano-lavori-2023',
            '@type': 'Documento',
            CreationDate: '2023-01-04T09:18:56+00:00',
            Creator: 'admin',
            Date: '2023-01-19T12:04:48+00:00',
            Description:
              'Deliberazione del Consiglio comunale per piano lavori previsto per il 2023',
            EffectiveDate: 'None',
            ExpirationDate: 'None',
            ModificationDate: '2023-01-19T12:04:48+00:00',
            Subject: [],
            Subject_bando: null,
            Title: 'Piano lavori 2023',
            Type: 'Documento',
            UID: 'f06b6a6930794563bcb2cee3889b9b0b',
            apertura_bando: null,
            author_name: null,
            chiusura_procedimento_bando: null,
            cmf_uid: 91,
            commentators: [],
            created: '2023-01-04T09:18:56+00:00',
            data_conclusione_incarico: null,
            description:
              'Deliberazione del Consiglio comunale per piano lavori previsto per il 2023',
            design_italia_meta_type: 'Documento',
            destinatari_bando: null,
            effective: null,
            end: null,
            ente_bando: null,
            event_location: null,
            exclude_from_nav: false,
            expires: null,
            geolocation: null,
            getIcon: false,
            getId: 'piano-lavori-2023',
            getObjSize: '0 KB',
            getPath:
              '/Plone/documenti-e-dati/documenti-albo-pretorio/piano-lavori-2023',
            getRemoteUrl: null,
            getURL:
              'http://localhost:3000/documenti-e-dati/documenti-albo-pretorio/piano-lavori-2023',
            hasPreviewImage: null,
            head_title: null,
            icona: null,
            id: 'piano-lavori-2023',
            image_field: '',
            image_scales: null,
            in_response_to: null,
            is_folderish: true,
            last_comment_date: null,
            latitude: null,
            listCreators: ['admin'],
            location: null,
            longitude: null,
            mime_type: 'text/plain',
            modified: '2023-01-19T12:04:48+00:00',
            nav_title: null,
            open_end: null,
            parent: {
              '@id':
                'http://localhost:8080/Plone/documenti-e-dati/documenti-albo-pretorio',
              UID: '5e6600a7ce2245199b0986471cffcf17',
              title: 'Documenti albo pretorio',
            },
            portal_type: 'Documento',
            recurrence: null,
            review_state: 'private',
            scadenza_bando: null,
            start: null,
            sync_uid: null,
            tassonomia_argomenti: [],
            taxonomy_business_events: [],
            taxonomy_person_life_events: [],
            taxonomy_temi_dataset: [],
            taxonomy_tipologia_documenti_albopretorio: [],
            taxonomy_tipologia_documento: [],
            taxonomy_tipologia_evento: [],
            taxonomy_tipologia_frequenza_aggiornamento: [],
            taxonomy_tipologia_incarico: [],
            taxonomy_tipologia_licenze: [],
            taxonomy_tipologia_luogo: [],
            taxonomy_tipologia_notizia: [],
            taxonomy_tipologia_organizzazione: [],
            taxonomy_tipologia_pdc: [],
            taxonomy_tipologia_stati_pratica: [],
            tipologia_bando: null,
            tipologia_documento: null,
            tipologia_notizia: null,
            title: 'Piano lavori 2023',
            total_comments: 0,
            ufficio_responsabile_bando: null,
            update_note: null,
            whole_day: null,
          },
        ],
        total: 2,
        loaded: true,
        loading: false,
        batching: {},
      },
    },
  },
});

test('renders all mandatory fields in the page', async () => {
  render(
    <Provider store={store}>
      <MemoryRouter>
        <IncaricoView content={mock_mandatory} />
      </MemoryRouter>
    </Provider>,
  );

  //title
  expect(
    screen.getByRole('heading', { name: /Band leader/i }),
  ).toBeInTheDocument();

  // data inizio incarico --> non appare
  expect(screen.getByText('26/01/2023')).toBeInTheDocument();

  // tipologia incarico --> non appare
  expect(screen.getByText(/altro/i)).toBeInTheDocument();
});

test('renders all non-mandatory fields in the page', async () => {
  render(
    <Provider store={store}>
      <MemoryRouter>
        <IncaricoView content={mock_allfields} />
      </MemoryRouter>
    </Provider>,
  );

  //descrizione
  expect(screen.getByText(/Too late/i)).toBeInTheDocument();

  //persona che ha carica e incarico
  expect(screen.getByRole('heading', { name: /Persona/i })).toBeInTheDocument();
  expect(
    screen.getByRole('link', { name: /Gianluca Luchetti/i }),
  ).toBeInTheDocument();

  // unità organizzativa
  expect(
    screen.getByRole('heading', { name: /Unita organizzativa/i }),
  ).toBeInTheDocument();
  expect(
    screen.getByRole('link', {
      name: /Area impiantistica sportiva e manifestazioni sportive/i,
    }),
  );

  //responsabile struttura
  expect(
    screen.getByRole('heading', { name: /Responsabile/i }),
  ).toBeInTheDocument();
  expect(
    screen.getByRole('link', {
      name: /CTM Cagliari/i,
    }),
  ).toBeInTheDocument();

  //compensi
  expect(
    screen.getByRole('heading', { name: /Compensi/i }),
  ).toBeInTheDocument();
  expect(screen.getByText(/My time has come/i)).toBeInTheDocument();

  // importi di viaggio e di servizio
  expect(
    screen.getByRole('heading', { name: 'Importi di viaggio e/o servizio' }),
  ).toBeInTheDocument();
  expect(screen.getByText(/Sends shivers down my spine/i)).toBeInTheDocument();

  // data inizio incarico --> non appare
  expect(screen.getByText('31/03/2023')).toBeInTheDocument();
  // data insediamento  --> non appare
  expect(screen.getByText('31/01/2023')).toBeInTheDocument();

  // Atto di nomina --> pagina non renderizza quando selezionato
});
