# syntax=docker/dockerfile:1
ARG VOLTO_VERSION
FROM plone/frontend-dev:${VOLTO_VERSION}

ARG ADDON_NAME
ARG ADDON_PATH

USER root

RUN <<EOT
    set -e
    apt update
    apt install -y --no-install-recommends ca-certificates git-core libvips-dev
    rm -rf /var/lib/apt/lists/*
EOT

USER node

COPY --chown=node:node package.json /app/packages/${ADDON_PATH}/
COPY --chown=node:node dockerfiles/helper.js /app/

RUN --mount=type=cache,id=pnpm,target=/app/.pnpm-store,uid=1000 <<EOT
    set -e
    node helper.js
    CI=true pnpm install --fetch-timeout 600000 --shamefully-hoist --no-frozen-lockfile
EOT
