version: '3'

services:
  addon-dev:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile.dev
      args:
        ADDON_NAME: '${ADDON_NAME}'
        ADDON_PATH: '${ADDON_PATH}'
        VOLTO_VERSION: ${VOLTO_VERSION:-16}
    volumes:
      - ${CURRENT_DIR}:/app/src/addons/${ADDON_PATH}/
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
      RAZZLE_API_PATH: http://localhost:8080/Plone
    ports:
      - 3000:3000
      - 3001:3001
    tty: true
    profiles:
      - dev
      - unittest

    # Use these to debug
    # stdin_open: true
    # entrypoint: ''
    # command: /bin/bash

  addon-prod:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile
      args:
        ADDON_NAME: '${ADDON_NAME}'
        ADDON_PATH: '${ADDON_PATH}'
        VOLTO_VERSION: ${VOLTO_VERSION:-16}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
      RAZZLE_API_PATH: http://localhost:8080/Plone
    ports:
      - 3000:3000
    tty: true
    profiles:
      - prod

  backend:
    # image: plone/plone-backend:${PLONE_VERSION:-6}
    image: ghcr.io/redturtle/iocomune-backend:latest
    environment:
      SITE: Plone
      PROFILES: design.plone.policy:default
      CORS_ALLOW_ORIGIN: '*'
    ports:
      - 8080:8080
    profiles:
      - dev
      - prod
