# syntax=docker/dockerfile:1
ARG VOLTO_VERSION
FROM plone/frontend-dev:${VOLTO_VERSION}

ARG ADDON_NAME
ARG ADDON_PATH

USER root

RUN <<EOT
    set -e
    apt update
    apt install -y --no-install-recommends ca-certificates git-core libvips-dev
    rm -rf /var/lib/apt/lists/*
EOT

USER node

COPY --chown=node:node package.json /app/src/addons/${ADDON_PATH}/

RUN <<EOT
    set -e
    /setupAddon
    yarn install --network-timeout 1000000
EOT
