name: Docker build for latest alpha version
on:
  push:
    branches: [design-react-kit-v4]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: redturtletech/io-comune-base:alpha
          pull: true
          push: true
          cache-from: type=registry,ref=redturtletech/io-comune-base:alpha
          cache-to: type=inline

      - name: Deploy to rancher
        uses: redturtle/rancher-deploy-action@v0.1.0
        with:
          host: ${{ secrets.RANCHER_HOST }}
          api-username: ${{ secrets.RANCHER_API_USERNAME }}
          api-password: ${{ secrets.RANCHER_API_PASSWORD }}
          cluster-id: ${{ secrets.RANCHER_CLUSTER_ID }}
          project-id: ${{ secrets.RANCHER_PROJECT_ID }}
          namespace: ${{ secrets.RANCHER_NAMESPACE_DEVELOP }}
          workload: ${{ secrets.RANCHER_WORKLOAD_ALPHA }}
          image: redturtletech/io-comune-base:alpha
          slack-hook-url: ${{ secrets.RANCHER_SLACK_HOOK_URL }}
